---
title: "Software"
editor: visual
---

## `regrake`

An R package for regularized raking, based on the optimization framework of [Barratt, Angeris, and Boyd (2021)](https://doi.org/10.1007/s11222-021-10001-1). `regrake` enables more flexible functional forms in raking to population targets — mixing exact and soft (L2) constraints, supporting meaningful regularization, and ultimately producing more expressive and efficient survey weights. It features a `brms`-inspired formula interface and accepts a wide variety of target input formats.

```{=html}
    <a class="btn btn-outline-dark btn-sm" href="https://stanford.edu/~boyd/papers/optimal_representative_sampling.html" target="_blank" rel="noopener noreferrer">
        <i class="bi bi-file-text" role="img" aria-label="Original Paper"></i>
        Original Paper
    </a> <a class="btn btn-outline-dark btn-sm" href="https://andytimm.github.io/posts/announcing_regrake/announcing_regrake.html" target="_blank" rel="noopener noreferrer">
        <i class="bi bi-info" role="img" aria-label="Website"></i>
        Website
    </a> <a class="btn btn-outline-dark btn-sm" href="https://github.com/andytimm/regrake" target="_blank" rel="noopener noreferrer">
        <i class="bi bi-github" role="img" aria-label="Github"></i>
        Github
    </a>
```

## `rswjax`

A [JAX](https://github.com/google/jax) implementation of optimal representative sample weighting, drawing heavily on the original `rsw` implementation of Barratt, Angeris, and Boyd ([rsw](https://github.com/cvxgrp/rsw/tree/master)). Thanks to rewriting some core operations in JAX, it is significantly faster than `rsw` for medium-large datasets, especially those with many columns (ex: 5k+ rows, 20+ columns). While JAX isn't the most natural fit here, this was a fun way to build something complex, and practice making it fast with JAX! I started this project because of my interest in [regularized raking](https://andytimm.github.io/posts/NYSOPM_talk_regularized_raking/NYOSPM_talk.html), and wanting to iterate faster on large weighting problems.

```{=html}
    <a class="btn btn-outline-dark btn-sm" href="https://stanford.edu/~boyd/papers/optimal_representative_sampling.html" target="_blank" rel="noopener noreferrer">
    <i class="bi bi-file-text" role="img" aria-label="Original Paper"></i>
    Original Paper
</a>
    </a> <a class="btn btn-outline-dark btn-sm" ,="" href=https://github.com/andytimm/rswjax target="_blank" rel="noopener noreferrer">
        <i class="bi bi-github" role="img" aria-label="Github"></i>
        Github
    </a> <a class="btn btn-outline-dark btn-sm" ,="" href="https://pypi.org/project/rswjax/" target="_blank" rel="noopener noreferrer">
        <i class="bi bi-box-seam" role="img" aria-label="Package"></i>
        Package
    </a>
```

## `retrodesign`

`retrodesign` provides tools for working with Type S (Sign) and Type M (Magnitude) errors, as proposed in [Gelman and Tuerlinckx (2000)](https://link.springer.com/article/10.1007/s001800000040) and [Gelman & Carlin (2014)](https://journals.sagepub.com/doi/full/10.1177/1745691614551642). In addition to simply calculating the probability of Type S/M error, the package includes functions for calculating these errors across a variety of effect sizes for comparison, and recommended sample size given "tolerances" for Type S/M errors. To improve the speed of these calculations, closed forms solutions for the probability of a Type S/M error from [Lu, Qiu, and Deng (2018)](https://pubmed.ncbi.nlm.nih.gov/29569719/) are implemented. The broader goal of this project was to make it easier for researchers to understand these issues in their work, and it's gratifying the package has been able to do that.

```{=html}
<a class="btn btn-outline-dark btn-sm" ,="" href="https://andytimm.github.io/posts/Intro%20to%20Retrodesign/2019-02-05-Intro_To_retrodesign.html" target="_blank" rel="noopener noreferrer">
        <i class="bi bi-info" role="img" aria-label="Website"></i>
        Website
    </a> <a class="btn btn-outline-dark btn-sm" ,="" href="https://github.com/andytimm/retrodesign" target="_blank" rel="noopener noreferrer">
        <i class="bi bi-github" role="img" aria-label="Github"></i>
        Github
    </a> <a class="btn btn-outline-dark btn-sm" ,="" href="https://cran.r-project.org/web/packages/retrodesign/index.html" target="_blank" rel="noopener noreferrer">
        <i class="bi bi-box-seam" role="img" aria-label="Package"></i>
        Package
    </a>
```
