---
layout: post
title: Variational Inference for MRP with Reliable Posterior Distributions
subtitle: Part 2
date: 2022-10-28
draft: True
categories:
- MRP
- BART
- Variational Inference
---

This is the second post in my series on using Variational Inference to speed up relatively complex Bayesian like Multilevel Regression and Poststratification models without the approximation being of disastrously poor quality. In the last post, I laid out why such reformulating the Bayesian inference problem as optimization might be desirable, but previewed why this might be quite hard to find high quality approximations amenable to optimization. I then introduced our running example (predicting national/sub-national opinion on an abortion question form the CCES using MRP), and gave an initial introduction to a version of Variational Inference where we maximize the Evidence Lower Bound (ELBO) as an objective, and do so using a mean-field Gaussian approximation. We saw that with 60k examples, this took about 8 hours to fit with MCMC, but 144 seconds (!) with VI.

In this post, we'll explore the shortcomings of this initial approximation, and take a first pass at trying to better with a more complex (full rank) variational approximation. The goal is to get a better feel for what failing models could look like, at least in this relatively simple case.

The rough plan for the series is as follows:

1.  [Introducing the Problem- Why is VI useful, why VI can produce spherical cows](https://andytimm.github.io/posts/Variational%20MRP%20Pt1/variational_mrp_pt1.html)
2.  **(This post)** How far does iteration on classic VI algorithms like mean-field and full-rank get us?
3.  Some theory on why posterior approximation with VI can be so poor
4.  Seeing if some more sophisticated techniques like normalizing flows help

# The disclaimer

One sort of obvious objections to how I've set up this series is "Why not talk about theory on why VI approximations can be poor before trying stuff?". While in practice I did read a lot of the papers for the next post before writing this one, I think there's a lot of value is looking at failed solutions to a problem to build up intuition about what our failure mode looks like, and what it might require to get it right. <Example or two to tease this once I have them>.

# The dumbest possible test

# Toplines

# State Level Estimates

# More Subtle Interactions

# Do 'Minor' corrections solve anything?

## Lowering the tolerance

## What if we evaluate Holdout ELBO

# Where to from here? (Why is it like this!?)